### ISSUE TITLE
Feat: Landing 페이지 제작

### ISSUE THREAD

**Issue by hyemeeny** [FE-J5/fandom-k#22]
## 🚀 Description
랜딩 페이지 

## ✅ TODO
- [x] pages/Landing.jsx
- [x] hooks/useScrollAnimation.jsx 
- [x] components/DescriptionContent.jsx
- [x] 지금 시작하기 버튼 추가
